"""initial

Revision ID: 5c04fdd65b09
Revises: 6266e7637a9d
Create Date: 2025-12-12 10:41:40.011511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c04fdd65b09'
down_revision = '6266e7637a9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
